#!/usr/bin/env bash


script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter="$1"

echo "$script_dir -- $filter"

cd $script_dir
# we are truying to loop through the scripts without folling into the recurrsion
# scripts=$(find ./runs -maxdepth 1 -mindepth 1 -executable -type f) - this one on linux
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -type f -exec test -x {} \; -print)


for script in $scripts; do
    if echo "$script" | grep -qv "$filter"; then
        echo "filtering $script"
        continue
    fi

    ./$script
done


